"""empty message

Revision ID: af4a1a638b0e
Revises: 05cca9722162
Create Date: 2022-06-02 05:21:22.991495

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4a1a638b0e'
down_revision = '05cca9722162'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_listed', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('date_listed', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'date_listed')
    op.drop_column('artists', 'date_listed')
    # ### end Alembic commands ###
